# This file is a template, and might need editing before it works on your project.
# This is the Gradle build system for JVM applications
# https://gradle.org/
# https://github.com/gradle/gradle
image: git.the9grounds.com:5050/minecraft/aeadditions/gradle-docker:latest

# Disable the Gradle daemon for Continuous Integration servers as correctness
# is usually a priority over speed in CI environments. Using a fresh
# runtime for each build is more reliable since the runtime is completely
# isolated from any previous builds.
variables:
  GRADLE_OPTS: "-Dorg.gradle.daemon=false"

before_script:
  - export GRADLE_USER_HOME=`pwd`/.gradle

buildNonRelease:
  stage: build
  script: sh ./gradlew --build-cache setupCiWorkspace assemble
  except:
    - tags
  artifacts:
    paths:
      - build/libs/*.jar
  cache:
    key: "$CI_COMMIT_BRANCH"
    policy: pull-push
    paths:
      - .gradle


buildRelease:
  stage: build
  only:
    - tags
  script:
    - sh ./gradlew gitChangelogTask
    - sh ./gradlew --build-cache setupCiWorkspace assemble
  artifacts:
    paths:
      - build
      - CHANGELOG.md
  cache:
    key: "release-pipeline"
    policy: pull-push
    paths:
      - .gradle

deploy:
  stage: deploy
  only:
    - tags
  cache:
    key: "release-pipeline"
    policy: pull
    paths:
      - .gradle
  script:
    - sh ./gradlew curseforge493962
#test:
#  stage: test
#  script: sh ./gradlew check
#  cache:
#    key: "$CI_COMMIT_REF_NAME"
#    policy: pull
#    paths:
#      - build
#      - .gradle
